name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Setup network
        run:
          docker network create --driver bridge se-methodss
          docker pull mongo
          docker run -d --name mongo-dbserver --network se-methodss mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t se-methodss.
      - name: Run image
        run: docker run --network se-methodss --name devopscontainer sem
      - name: view logs
        run: docker logs devopscontainer