name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Setup network and Mongo
        run: |
          docker network create --driver bridge se-methodss
          docker pull mongo
          docker run -d --name mongo-dbserver --network se-methodss mongo

      # Wait until MongoDB is healthy (prevents app crash due to timing)
      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..10}; do
            if docker exec mongo-dbserver mongo --eval "db.adminCommand('ping')" >/dev/null 2>&1; then
              echo "MongoDB is ready!"
              break
            fi
            echo "MongoDB not ready yet... retrying in 5s"
            sleep 5
          done

      - name: Build with Maven
        run: mvn package

      - name: Build Docker image
        run: docker build -t se-methodss .

      - name: Run container
        run: docker run --network se-methodss --name devopscontainer se-methodss

      - name: View logs
        run: docker logs devopscontainer
