name: World Population App Workflow

on:
  push:

jobs:
  build:
    name: Build and Run World Population App
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set Up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Docker Compose
        run: docker compose up --abort-on-container-exit
