name: Global World Population CI/CD

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.MySQL_Test_Unit_Test test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # Uncomment below for private repos
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          verbose: true

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Start MySQL container
        run: docker compose up -d db

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for database to initialize..."
          sleep 20

      - name: Run Integration Tests
        run: mvn -Dtest=com.napier.sem.MySQL_Test_Integration_Test test

      - name: Shutdown Docker
        run: docker compose down

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          # Uncomment below for private repos
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: integrationtests
          verbose: true

  BuildAndDeploy:
    name: Build and Run in Docker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Build project (create devops.jar)
        run: mvn clean package -DskipTests

      - name: Verify devops.jar exists
        run: ls -l ./target

      - name: Build and Run Docker Compose
        run: |
          docker compose build
          docker compose up --abort-on-container-exit
